const CREATE_USER = 'CREATE_USER';
const REMOVE_USER = 'REMOVE_USER';
const CREATE_LEAD = 'CREATE_LEAD';
const EDIT_LEAD = 'EDIT_LEAD';
const START_SERVICE = 'START_SERVICE';
const EDIT_SERVICE = 'EDIT_SERVICE';
const ALL_DETAILS = 'ALL_DETAILS';
const MAKE_CONTACT = 'MAKE_CONTACT';

export default {
	CREATE_USER,
	REMOVE_USER,
	CREATE_LEAD,
	EDIT_LEAD,
	START_SERVICE,
	EDIT_SERVICE,
	ALL_DETAILS,
	MAKE_CONTACT
};
